version: '3.2'
services:
  backend1:
    build: ./backend
    tty: true
    volumes:
      - './backend/src:/backend-dir-inside-container'

  backend2:
    build: ./backend
    tty: true
    volumes:
      - './backend/src:/backend-dir-inside-container'

  backend3:
    build: ./backend
    tty: true
    volumes:
      - './backend/src:/backend-dir-inside-container'

  loadbalancer:
    build: ./load-balancer
    tty: true
    links:
      - backend1
      - backend2
      - backend3
    ports:
      - '8080:8080'
    volumes:
      - ${pwd}/logs/nginx-error.log:/var/log/nginx/error.log
      - ${pwd}/logs/nginx-access.log:/var/log/nginx/access.log

volumes:
  backend: